---
id: Rpc
name: Rpc
full: RPC library
description: A library providing various remote methods of accessing Horde functionality.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Rpc
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: developer
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Core: ^2.5
      pear.horde.org/Horde_Dav: ^1
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Serialize: ^2
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_Xml_Element: ^2
  optional:
    pear:
      pear.horde.org/Horde_ActiveSync: ^2
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Lock: ^2
      pear.horde.org/Horde_SyncMl: ^2
    ext:
      soap: '*'
      xmlrpc: '*'
