---
id: Rpc
name: Rpc
full: RPC library
description: A library providing various remote methods of accessing Horde functionality.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Rpc
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: developer
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/core: ^3
      horde/dav: ^2
      horde/exception: ^3
      horde/perms: ^3
      horde/serialize: ^3
      horde/support: ^3
      horde/translation: ^3
      horde/util: ^3
      horde/xml_element: ^3
  optional:
    composer:
      horde/activesync: ^3
      horde/http: ^3
      horde/lock: ^3
      horde/syncml: ^3
    ext:
      soap: '*'
      xmlrpc: '*'
